spring:
    datasource:
        url: jdbc:mysql://localhost:3306/${DB_DATABASE}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: create
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

---
spring:
    profiles: container
    datasource:
        url: jdbc:mysql://${DB_HOST}:3306/${DB_DATABASE}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
